# Generated by Django 4.2 on 2025-01-02 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.DateField(validators=[django.core.validators.RegexValidator(message='Enter a valid birth date in the format YYYY-MM-DD.', regex='^(19|20)\\d{2}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$')])),
                ('number_of_authored_books', models.SmallIntegerField(max_length=3)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_day', models.DateField(auto_now_add=True)),
                ('ISBN', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
